language: python
python:
  - "2.7"
before_install:
  - sudo pip install --upgrade conda
install:
  # install deps
  - sudo conda init
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8 pylint'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install unittest2
  # install our own package into the environment
  - "pip install ."
script:
  # Download spark 1.4.0
  - "wget http://download.nextag.com/apache/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.4.tgz"
  - "tar -xvf spark-1.4.0-bin-hadoop2.4.tgz"
  # build our scala code
  - ./sbt/sbt compile package
  # Run the tests
  - "export SPARK_HOME=./spark-1.4.0-bin-hadoop2.4/"
  - "./run-tests"
  - "pep8 --ignore=E402 sparklingpandas/"
  - "pylint -E sparklingpandas --extension-pkg-whitelist=numpy"
  