language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo pip install --upgrade conda
install:
  # install deps
  - sudo conda init
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install unittest2
  # install our own package into the environment
  - "pip install ."
script:
  # Download spark 1.2.0
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.2.0-bin-hadoop2.4.tgz"
  - "tar -xvf spark-1.2.0-bin-hadoop2.4.tgz"
  # Run the tests
  - "export SPARK_HOME=./spark-1.2.0-bin-hadoop2.4/"
  - "./run-tests"
  - "pep8 --ignore=E402 sparklingpandas/"